### ISSUE TITLE
Animation on change

### ISSUE THREAD

**Issue by Usmani7** [Hitesh822/draggable_bottom_sheet_package#1]
Thank you for this amazing plugin. Should not there be some animation while expanding the sheet?

**Comment by Hitesh822** [comment]
> Thank you for this amazing plugin. Should not there be some animation while expanding the sheet?

Yeah, i have plans for this in near future. Also the code contributions are welcomed.

**Comment by Hitesh822** [comment]
Hi @Usmani7
Now bottom sheet is wrapped into an AnimatedContainer which will provide you with some animation. 
And you are completely free to make any animation in your `previewWidget` & `expandedWidget`.
